### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by xbclub** [zkhssb/NectarRCON#8]
版本：1.0.0-beta4
环境：windows11
服务器环境：ubuntu22.04 帕鲁服务
问题描述： 在链接服务器时与断线重连时有较大概率程序闪退崩溃
日志：未找到崩溃相关日志 logs文件夹下只有服务器命令执行日志

**Comment by vulgarLover** [comment]
版本：1.0.0-beta4
环境：win10
服务器：centos7.6 幻兽帕鲁
问题：
![image](https://github.com/zkhssb/NectarRCON/assets/45785738/dc5f8d19-2d82-4933-b67a-b783b52bbba3)
loading一会直接闪退，没有链接成功过

**Comment by vulgarLover** [comment]
我的原因找到了，因为ip是复制上去的，末尾多了一个空格，空格删掉 @xbclub 你看下你是不是这个问题
@zkhssb 作者可以优化下，自动去除ip首尾的空格

**Comment by xbclub** [comment]
> 我的原因找到了，因为ip是复制上去的，末尾多了一个空格，空格删掉 @xbclub 你看下你是不是这个问题 @zkhssb 作者可以优化下，自动去除ip首尾的空格

我从server.json 确认了下 没有空格

**Comment by zkhssb** [comment]
正在检查!

**Comment by zkhssb** [comment]
麻烦更新到[1.0.0-beta5](https://github.com/zkhssb/NectarRCON/releases/tag/v1.0.0-beta5)看看报错具体是什么

**Comment by xbclub** [comment]
更新后暂时没遇到闪退的情况，我再继续观察一阵，thanks。

> 麻烦更新到[1.0.0-beta5](https://github.com/zkhssb/NectarRCON/releases/tag/v1.0.0-beta5)看看报错具体是什么

**Comment by xbclub** [comment]
> 麻烦更新到[1.0.0-beta5](https://github.com/zkhssb/NectarRCON/releases/tag/v1.0.0-beta5)看看报错具体是什么

重连异常了，但是没有闪退，最新日志如下：
```
2024-01-26 11:02:22.165 +08:00 [INF] [Run] showplayers
2024-01-26 11:02:22.200 +08:00 [INF] 当前客户端状态: 离线
2024-01-26 11:02:25.521 +08:00 [INF] [ReConnectCommand] 正在准备重连
2024-01-26 11:02:25.521 +08:00 [INF] 当前客户端状态: 离线
2024-01-26 11:02:25.521 +08:00 [INF] [ConnectAsync] 准备连接到服务器
2024-01-26 11:02:25.521 +08:00 [INF] [ConnectAsync] 连接服务: NectarRCON.Services.RconSingleConnection, 是否为多连接: False
2024-01-26 11:02:25.766 +08:00 [ERR] [ConnectAsync] 连接遇到错误: DnsClient.DnsResponseException: Query 42910 => _minecraft._tcp.192.168.66.35 IN SRV on 192.168.66.254:53 timed out or is a transient error.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at DnsClient.DnsUdpMessageHandler.Query(IPEndPoint server, DnsRequestMessage request, TimeSpan timeout)
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
   at DnsClient.LookupClient.QueryInternal(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers)
   at NectarRCON.Core.Helper.DNSHelpers.SRVQuery(String host)
   at NectarRCON.Services.RconSingleConnection.Connect()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at NectarRCON.ViewModels.MainPageViewModel.ConnectAsync()
2024-01-26 11:02:28.908 +08:00 [INF] 当前客户端状态: 离线
2024-01-26 11:02:28.914 +08:00 [INF] 当前客户端状态: 离线
```

**Comment by git-cshong** [comment]
版本：1.0.0-beta5
环境：windows11
服务器环境：windows server 2016 帕鲁服务
问题描述： 在链接服务器时与断线重连时有较大概率程序闪退崩溃
日志：未找到崩溃相关日志 logs文件夹下只有服务器命令执行日志
![image](https://github.com/zkhssb/NectarRCON/assets/79447337/237a27c7-b3bf-4a21-84ca-3038eaf17f21)
偶发性崩溃，还有返回的内容只有前面的一部分，并不完整
![QQ图片20240126165442](https://github.com/zkhssb/NectarRCON/assets/79447337/9615c1a3-07e7-400c-828e-ea05ed7d581b)
